### PR TITLE
RNMT-2921 [InAppBrowser] Can't open url with http in Android 9

### PR DESCRIPTION
**Pull request by usernuno**
## Description

Added a hook that conditionally sets `cleartextTrafficPermitted` in `network_security_config.xml` to true. The condition is based on the value of an OS extensibility preference:

Screenshot 2019-05-31 at 18 54 45

## Context

Fixes https://outsystemsrd.atlassian.net/browse/RNMT-2921

Historically this plugin has always supported plain HTTP requests.
But when building with target API 28 and using an Android 9+ device its support is disabled by default.
This support can be enabled by setting the `cleartextTrafficPermitted` property in `network_security_config.xml` to true.

## Type of changes

- [ ] Feature (change which adds functionality)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to new feature)
- [x] Fix (change which fixes an issue)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to fix)
- [ ] Performance (change which improves performance)
    - [ ] BREAKING CHANGE (existing functionality will not work as expected due to performance improvement)
- [ ] Refactor (non-breaking change that is neither feature, fix nor performance)
- [ ] Style (non-breaking change that only affects formatting and/or white-space)

## Components affected
- [x] Android platform
- [ ] iOS platform
- [x] JavaScript
- [ ] OutSystems

## Tests

Manual tests were performed:
- Tested both HTTP and HTTPS requests
- Tested with an Android 7, Android 9 and iOS 12 device
- Tested with MABS 4.2 and 5.0
- Tested by enabling the property, disabling it and not defining it
- Tested both the in-app browser and the open in system browser options

Everything worked except for the combinations:
- HTTP request
- Android 9 device
- MABS 5.0
- Disabling or not defining the property
- In-app browser

This is the expected result, since it is the problematic case without enabling the feature.

## Checklist

- [x] Pull request title follows the format `RNMT-XXXX <title>`
- [ ] Tests have been created
- [x] Code follows code style of this project
- [ ] CHANGELOG.md file is correctly updated
- [x] Changes require an update to the documentation
	- [ ] Documentation has been updated accordingly

### CODE REVIEW

**Comment by usernuno** [comment]
Keep in mind that any error that occurs in the hook will make the build process fail. Please validate if any type of exception handling should be added and where.

I'd say that `shouldEnableCleartextTrafficPermitted` is a good candidate for a try/catch that returns false on failure. There is a remote possibility of the `config.xml` failing to read or `$` not existing in a platform or preference.

**Comment by luissilvaos** [comment]
I’m just concerned only with the size of the  name chosen for the preference. Can’t we have a shorter one? Or can we use plugin variables instead of app preferences?

**Comment by EiyuuZack** [comment]
Why is the `node_modules` folder being brought into the repository?

**Comment by usernuno** [comment]
> Why is the `node_modules` folder being brought into the repository?

Same reasoning as the one in the PushWoosh plugin. This way the installation process is not required, making the hook faster and less error prone.

**Comment by usernuno** [comment]
> I’m just concerned only with the size of the name chosen for the preference. Can’t we have a shorter one? Or can we use plugin variables instead of app preferences?

The preference name is up for discussion.

**Comment by vmfo22** [comment]
> I just have one change request. The preference should more user-friendly like `InAppBrowserHTTPEnabled` or `InAppBrowserCleartextTrafficPermitted`.

I have a concern by adding the InAppBrowser as a prefix because by adding the preference the clear text traffic will be allowed for all requests in the app and not only in the context of InAppBrowser plugin.

**Comment by luissilvaos** [comment]
@vmfo22 the idea of adding the InAppBrowser to the preference is just to contextualize it. Having a preference called `EnableClearttextTraffic` can be misleading since it will require the usage of the InAppBrowser plugin for that feature.

**Comment by usernuno** [comment]
The preference name has been updated as requested.

**Pull request merged**
